In [1]:
import pandas as pd

df=pd.read_csv("cleaned_titanicDataset")

How much the size of the data ?

In [2]:
df.shape

(1309, 9)

How's the data look like ?

In [3]:
df.sample(5) #if i do df.head() or df.tail() it will give me first or last rows may be it looks like same i cat analyze better that that's why i use df.sample for random data

,Passengerid,Age,Fare,Sex,sibsp,Parch,Pclass,Embarked,survived
792,793,28.0,69.5500,1,8,2,3,2.0,0
1014,1015,28.0,7.2500,0,0,0,3,2.0,0
1225,1226,27.0,7.8958,0,0,0,3,2.0,0
1264,1265,44.0,13.0000,0,0,0,2,2.0,0
1074,1075,28.0,7.7500,0,0,0,3,1.0,0

what are the types of data ?

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Passengerid  1309 non-null   int64
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64
 4   sibsp        1309 non-null   int64
 5   Parch        1309 non-null   int64
 6   Pclass       1309 non-null   int64
 7   Embarked     1307 non-null   float64
 8   survived     1309 non-null   int64
dtypes: float64(3), int64(6)
memory usage: 92.2 KB

Is there any null value ?

In [5]:
df.isnull().sum()

Passengerid    0
Age            0
Fare           0
Sex            0
sibsp          0
Parch          0
Pclass         0
Embarked       2
survived       0
dtype: int64

Is there any duplicated values ?

In [11]:
df.duplicated().sum()

np.int64(0)

How data looks mathematically ?

In [12]:
df.describe()

,Passengerid,Age,Fare,Sex,sibsp,Parch,Pclass,Embarked,survived
count,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1307.000000,1309.000000
mean,655.000000,29.503186,33.281086,0.355997,0.498854,0.385027,2.294882,1.492731,0.261268
std,378.020061,12.905241,51.741500,0.478997,1.041658,0.865560,0.837836,0.814626,0.439494
min,1.000000,0.170000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,328.000000,22.000000,7.895800,0.000000,0.000000,0.000000,2.000000,1.000000,0.000000
50%,655.000000,28.000000,14.454200,0.000000,0.000000,0.000000,3.000000,2.000000,0.000000
75%,982.000000,35.000000,31.275000,1.000000,1.000000,0.000000,3.000000,2.000000,1.000000
max,1309.000000,80.000000,512.329200,1.000000,8.000000,9.000000,3.000000,2.000000,1.000000

Is there any correlation between the data ?

In [13]:
df.corr(numeric_only=True)

,Passengerid,Age,Fare,Sex,sibsp,Parch,Pclass,Embarked,survived
Passengerid,1.000000,0.025799,0.031128,-0.013406,-0.055224,0.008942,-0.038354,-0.051518,-0.331493
Age,0.025799,1.000000,0.178182,-0.053663,-0.189972,-0.125851,-0.377908,-0.065125,-0.055862
Fare,0.031128,0.178182,1.000000,0.185681,0.160349,0.221635,-0.558683,-0.239212,0.173786
Sex,-0.013406,-0.053663,0.185681,1.000000,0.109609,0.213125,-0.124617,-0.099408,0.404020
sibsp,-0.055224,-0.189972,0.160349,0.109609,1.000000,0.373587,0.060832,0.066055,-0.014375
Parch,0.008942,-0.125851,0.221635,0.213125,0.373587,1.000000,0.018322,0.045216,0.054908
Pclass,-0.038354,-0.377908,-0.558683,-0.124617,0.060832,0.018322,1.000000,0.187349,-0.244686
Embarked,-0.051518,-0.065125,-0.239212,-0.099408,0.066055,0.045216,0.187349,1.000000,-0.093225
survived,-0.331493,-0.055862,0.173786,0.404020,-0.014375,0.054908,-0.244686,-0.093225,1.000000

In [15]:
df['Fare'].corr(df['survived'])

np.float64(0.17378625465251293)